### ISSUE TITLE
MethodNotSupported error when parsing brackets

### ISSUE THREAD

**Issue by dnicolson** [xinminlabs/synvert-core#11]
When using the [use_symbol_to_proc](https://github.com/xinminlabs/synvert-snippets/blob/master/lib/ruby/use_symbol_to_proc.rb) snippet at least two problems were encountered where brackets were used.

Lines 3 and 8 of this code caused `synvert-core` to raise a `MethodNotSupported` exception:

```class MyClass
  def method1
    super(params) do
    end
  end

  def method2(var)
    var.each do |(param1, param2)|
    end
  end
end
```

**Comment by flyerhzm** [comment]
@dnicolson I have released a new version synvert-core to fix this.

**Comment by dnicolson** [comment]
I found another instance where the error occurs:
```
class MyClass
  def method
    super do
    end
  end
end
```

**Comment by flyerhzm** [comment]
@dnicolson also fixed

**Comment by dnicolson** [comment]
I discovered another instance, it seems to be dependent on a certain directory structure so the following `bash` script should be able to reproduce it:

```
#!/bin/bash

mkdir test
cd test
touch Gemfile Gemfile.lock
mkdir -p app/controllers
cat > app/controllers/test_controller.rb <<- EOM
class TestController < ApplicationController
  def method(options)
    Model.scoped(options).find(:all)
  end
end
EOM

synvert -r rails/convert_models_2_3_to_3_0
```

**Comment by dnicolson** [comment]
And another:

```
#!/bin/bash

mkdir test
cd test
https://raw.githubusercontent.com/bbatsov/powerpack/v0.1.1/lib/powerpack/enumerable/exactly.rb

synvert -r ruby/use_symbol_to_proc
```

**Comment by flyerhzm** [comment]
@dnicolson fixed both, thanks for reporting errors.
